version: "1.0"
services:
  database:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - base-network
    container_name: database
    volumes:
      - nps_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 5

  blog:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: blog
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DB_HOST=database
      - POSTGRES_PORT=5432
    networks:
      - base-network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
volumes:
  nps_data: { }
networks:
  base-network:
